### ISSUE TITLE
Thanks! and also maybe put install instructions in the README.md?

### ISSUE THREAD

**Issue by u2berggeist** [lervag/vim-foam#1]
First off, thanks for making an recently-maintained vim plugin for OpenFOAM!

Second, it might be nice to have install instructions in the `README.md` for those who are unfamiliar with installing plugins (or as a general double check).

I can validate that:
```vim script
Plug 'lervag/vim-foam'
```
does indeed work fine for those using `vim-plug`

Edit: Also, I'm not overly familiar with OpenFOAM or vimscript, but if there's some small tasks to do, let me know!

**Comment by lervag** [comment]
Cool, I'm happy to see someone actually using this. I've recently started with OpenFOAM myself, and so I've begun writing a more sensible plugin for it. A lot of work remains, though, but I think the framework is pretty good.

I'll update the install instructions as suggested when I get the time!

For contributions: One of the main "simple" contributions would be to keep me posted on the various possible configuration options. If you see in `vim-foam/autoload/foam/case.vim`, you see that I am building a "catalog" of the various options. Obviuosly, it would be much better if I could parse this from some updated external source, but I am not aware of any such sources. Thus I've started to implement the catalog myself based on information from the main docs. This is tedious, but sort of worth it, because:
- This allows me to create useful completion candidates
- Allows possible syntax highlighting of errors (not added now, though)

In any case, thanks for the interest! I will probably be updating the plugin more this year when I get to work more specifically with OpenFOAM, probably this autumn.

**Comment by u2berggeist** [comment]
Cool! For the configuration options, I think the best way would be to go through the source code for different categories. For example:
```shell
u2berggeist@Exia00:~/gitRepos/vim-foam$ ls ~/OpenFOAM/OpenFOAM-v1712/src/finiteVolume/fields/fvPatchFields/basic/
basicSymmetry  coupled         extrapolatedCalculated  fixedValue  sliced     zeroGradient
calculated     directionMixed  fixedGradient           mixed       transform
```
These are the basic field patches available. 

However, the directory structure is not super clear, so I don't know how much help haphazardly trying to find directories that correspond with actual options would work. 

I'll try and look for the code that actual parses the dictionaries and see if that can lead us to something more consistent.
