### ISSUE TITLE
Create Options Catalog

### ISSUE THREAD

**Issue by jrwrigh** [lervag/vim-foam#2]
I'm going ahead and creating a separate issue for this (I don't have much open-source contribution experience, so just let me know if this should actually go somewhere else.

Main purpose here is to create a catalog of all the options that can go into OpenFOAM case files (`controlDict`, `fvSchemes`, `fvSolution`, etc).

**Comment by u2berggeist** [comment]
_from @u2berggeist :_

Cool! For the configuration options, I think the best way would be to go through the source code for different categories. For example:
```shell
u2berggeist@Exia00:~/gitRepos/vim-foam$ ls ~/OpenFOAM/OpenFOAM-v1712/src/finiteVolume/fields/fvPatchFields/basic/
basicSymmetry  coupled         extrapolatedCalculated  fixedValue  sliced     zeroGradient
calculated     directionMixed  fixedGradient           mixed       transform
```
These are the basic field patches available. 

However, the directory structure is not super clear, so I don't know how much help haphazardly trying to find directories that correspond with actual options would work. 

I'll try and look for the code that actual parses the dictionaries and see if that can lead us to something more consistent.

_copied from #1_

**Comment by u2berggeist** [comment]
I found a more robust way of getting a list of parameters for a specific setting. It's hilariously brute force as well: Misspell a parameter, and then the error message gives you the correct parameters available. 

Ex. For the cavity example, if I change 
```
ddtSchemes                                                                                                                                                                                                                                
 {                                                                                                                                                                                                                                         
     default         Euler;                                                                                                                                                                                                                
 }     
```
to      
```
ddtSchemes                                                                                                                                                                                                                                
 {                                                                                                                                                                                                                                         
     default         Eulers;                                                                                                                                                                                                                
 }     
```
In the error output is this beautiful message:

```
--> FOAM FATAL IO ERROR: 
Unknown ddt scheme Eulers

Valid ddt schemes are :

8
(
CoEuler
CrankNicolson
Euler
SLTS
backward
bounded
localEuler
steadyState
)
```

The actual code that brings that up is  in `OpenFOAM/OpenFOAM-v1712/src/finiteVolume/lnInclude/ddtScheme.C at line 76`

I've been digging through the API to try and figure out where the code gets that list, but my inexperience with C is getting in the way I think. If you want to take a look and see if you can parse

 I'll probably start on creating a Python script or something to run through a whole bunch of misspelled options and then regex out a list of the options given the output.

**Comment by u2berggeist** [comment]
Humorously, OpenFOAM documentation recommends doing the brute force method described above:

> ### **4.5.5 Other parameters**
> The fvSolutions dictionaries in the majority of standard OpenFOAM solver applications contain no other entries than those described so far in this section. However, in general the fvSolution dictionary may contain any parameters to control the solvers, algorithms, or in fact anything. **If any parameter or sub-dictionary is missing when an solver is run, it will terminate, printing a detailed error message. The user can then add missing parameters accordingly.**

_[source](https://cfd.direct/openfoam/user-guide/fvSolution/#x20-1570004.5.5)_

**Comment by u2berggeist** [comment]
I've started work on getting the python script to output the list of options. Work is being done in [FOAM_Options](https://github.com/u2berggeist/FOAM_Options). Currently I can launch `icoFoam` in a specific case directory, parse the output (assuming it has an error), and return a list of the options. 

Next step is to automate the editing of dictionaries.

**Comment by lervag** [comment]
I really appreciate your input here and the work on the python script. I think you might be onto something clever.

I think we would want to do something like this:

- Run the "FOAM_Options" script when loading a new foam buffer. This will give a good list/dictionary that describes the options and similar. Save this as part of the plugins buffer state.
- Let the completion function use this state as a basis for suggesting candidates.

The main difference from the current implementation is that I am now (not) maintaining a hard coded list of options.

I would also expect that such a list could be useful for more features, e.g. syntax highlighting "errors" (not sure if this is a good idea, though).

A requirement for the suggested feature is that the python script can return the list of options quickly, since this will be run for every buffer during initialization.

----

A side note: I assume we can rely on some of the built in utilities from OpenFOAM for more things. It makes sense to test during initialization if OpenFOAM is loaded (i.e. the `OpenFOAM/OpenFOAM-5.x/etc/bashrc` is loaded), and perhaps give a warning if not (or at least make a note of it and fail more gracefully if other stuff fail because of the environment not being loaded).

**Comment by u2berggeist** [comment]
Thanks! This is my first time actually contributing to something that wasn't my own, so the compliment really means something.

I agree that the having a dynamically updating list would be quite nice. It'd probably help a good bit if people make their own custom models/options as well. That said, I was mainly programming "FOAM_Options" as a solution to getting a hardcoded list, as there are still some idiosyncrasies to the method. For example, not every value change will create a list of options, or even raise an error. 

If we're wanting to go the auto-updating list, I think figuring out where the list comes from would probably be necessary. I also submitted a [forum post on CFD-Online](https://openfoamwiki.net/index.php/Contrib/PyFoam#Manipulating_dictionaries) about trying to figure out where exactly the list comes from, but haven't heard from anyone. I might bump it in a day or two. I feel like it really is just looking for filenames in a specific directory for each option, but I just can't figure out how to find out where it's looking.

----
For the `OpenFOAM/OpenFOAM-5.x/etc/bashrc` part, I would assume that it's going reliable as well. I initially tried to make a path to `icoFoam` directly (to reduce error problems), but it ended up running into more dependency issues related to not sourcing the `bashrc`.

**Comment by u2berggeist** [comment]
Update on the "How do they know whether a options is available?" problem; The list that is output through the error message comes from a [`runTimeSelectionTable`](https://openfoamwiki.net/index.php/OpenFOAM_guide/runTimeSelection_mechanism#Why_is_it_needed.3F). 

To my understanding, each "key" in the dictionary corresponds to a base class. So the "ddtSchemes" in the `fvSchemes` file corresponds to a `ddtSchemes.H` and `ddtSchemes.C` base class files. Those base classes contain the the "virtual constructor table" which houses the pointers to their derived classes (so `Euler` for example).

I have some stuff I need to get caught up on, otherwise I'd keep pursuing this. Big next step would be figuring out how to access the `runTimeSelectionTable` OR figure out how it's built. I'm guessing the former will be the easier way to go about it, but I'm not sure. 

In any case, I'll update the forum post to see if anyone can help us out anymore.
